name: Monitor Melon Ticket

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:       # 支持手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: mooyoul/melon-ticket-actions@v1
        with:
          product-id: '211408'
          schedule-id: '100001'
          seat-grade-id: '12215'
          notify-slack: true
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: mooyoul/melon-ticket-actions@v1
        with:
          product-id: '211408'
          schedule-id: '100002'
          seat-grade-id: '12215'
          notify-slack: true
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: mooyoul/melon-ticket-actions@v1
        with:
          product-id: '211408'
          schedule-id: '100003'
          seat-grade-id: '12215'
          notify-slack: true
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
